### PRODUCT YARATMA
POST http://localhost:8080/api/v1/products/create
Content-Type: application/json

{
  "name": "Telefon",
  "stock": 20,
  "price": 33.00,
  "description": "Telefon"
}


### PRODUCT GETIRME
GET http://localhost:8080/api/v1/products
Content-Type: application/json


### PRODUCT SILME
DELETE http://localhost:8080/api/v1/products/4243fb07-9b87-4158-ad93-711305d592e7
Content-Type: application/json


### URUNU GUNCELLE
PATCH http://localhost:8080/api/v1/products/7fe91fd5-80e1-4510-91a5-d2d5c5429a2e
Content-Type: application/json

{
  "stock": 50,
  "price": 30.00
}

